u = chr(95) + chr(95)
T = chr(9)
q = chr(34)
NL = chr(10)
L = []
L.append('# content_video5.py - shorts renderer (moviepy v2.1.x + PIL text)')
L.append('import os, sys, json, glob, numpy as np')
L.append('from PIL import Image, ImageDraw, ImageFont')
L.append('if not hasattr(Image, ' + q + 'ANTIALIAS' + q + '):')
L.append(T + 'Image.ANTIALIAS = Image.LANCZOS')
L.append('ROOT = os.path.dirname(os.path.dirname(os.path.abspath(' + u + 'file' + u + ')))')
L.append('sys.path.insert(0, ROOT)')
L.append('DB = os.path.join(ROOT, ' + q + 'memory' + q + ', ' + q + 'content_db.json' + q + ')')
L.append('FONT = ' + q + 'C:/Windows/Fonts/arialbd.ttf' + q)
L.append('TARGET = 13.0')
L.append('')
L.append('')
L.append('def load(kind):')
L.append(T + 'return json.load(open(DB, encoding=' + q + 'utf-8' + q + ')).get(kind, [])')
L.append('')
L.append('')
L.append('def _wrap(draw, text, font, maxw):')
L.append(T + 'words = text.split()')
L.append(T + 'lines = []')
L.append(T + 'cur = ' + q + q)
L.append(T + 'for w in words:')
L.append(T + T + 'test = (cur + ' + q + ' ' + q + ' + w).strip()')
L.append(T + T + 'if draw.textlength(test, font=font) <= maxw:')
L.append(T + T + T + 'cur = test')
L.append(T + T + 'else:')
L.append(T + T + T + 'if cur:')
L.append(T + T + T + T + 'lines.append(cur)')
L.append(T + T + T + 'cur = w')
L.append(T + 'if cur:')
L.append(T + T + 'lines.append(cur)')
L.append(T + 'return lines')
L.append('')
L.append('')
L.append('def text_frame(text, fs, color, W=720, H=1280, y=300):')
L.append(T + 'img = Image.new(' + q + 'RGBA' + q + ', (W, H), (0, 0, 0, 0))')
L.append(T + 'dr = ImageDraw.Draw(img)')
L.append(T + 'font = ImageFont.truetype(FONT, fs)')
L.append(T + 'lines = _wrap(dr, text, font, W - 80)')
L.append(T + 'lh = fs + 12')
L.append(T + 'cy = y')
L.append(T + 'for ln in lines:')
L.append(T + T + 'w = dr.textlength(ln, font=font)')
L.append(T + T + 'x = (W - w) / 2')
L.append(T + T + 'dr.text((x, cy), ln, font=font, fill=color, stroke_width=4, stroke_fill=' + q + 'black' + q + ')')
L.append(T + T + 'cy += lh')
L.append(T + 'return np.array(img)')
L.append('')
L.append('')
L.append('def make_scene(cpath, text, color, fs, dur, y, seed=0):')
L.append(T + 'from ops.compat import get_video_clip, concat as cc')
L.append(T + 'from ops.compat import _editor as _cmp_editor')
L.append(T + T + 'ColorClip = _cmp_editor()[5]')
L.append(T + T + 'VideoClip = cmp_editor()[0]')
L.append(T + 'V = get_video_clip()')
L.append(T + 'if cpath:')
L.append(T + T + 'b = V(cpath).resized(height=1280)')
L.append(T + 'else:')
L.append(T + T + 'b = ColorClip((720, 1280), color=(8, 10, 25), duration=dur)')
L.append(T + 'if b.w >= 720:')
L.append(T + T + 'b = b.cropped(width=720, x_center=b.w / 2)')
L.append(T + 'else:')
L.append(T + T + 'b = b.resized(width=720)')
L.append(T + 'if b.h < 1280:')
L.append(T + T + 'b = b.resized(height=1280)')
L.append(T + 'if b.duration < dur:')
L.append(T + T + 'n = int(dur / b.duration) + 1')
L.append(T + T + 'b = cc([b] + [b] * (n - 1))')
L.append(T + 'b = b.subclipped(0, dur)')
L.append(T + 'b = b.cropped(width=720, height=1280, x_center=b.w / 2, y_center=b.h / 2)')
L.append(T + 'col = (255, 255, 0) if color == ' + q + 'yellow' + q + ' else ((0, 255, 204) if color == ' + q + '#00ffcc' + q + ' else (255, 255, 255))')
L.append(T + 'overlay = text_frame(text, fs, col, 720, 1280, y)')
L.append(T + 'def mk(get, t):')
L.append(T + T + 'fr = get(t)')
L.append(T + T + 'ov = overlay.astype(' + q + 'float32' + q + ') / 255.0')
L.append(T + T + 'fr = fr.astype(' + q + 'float32' + q + ')')
L.append(T + T + 'out = fr * (1 - ov[..., 3:4]) + ov[..., :3] * 255 * ov[..., 3:4]')
L.append(T + T + 'return out.astype(' + q + 'uint8' + q + ')')
L.append(T + 'vid = VideoClip(lambda t: mk(b.get_frame, t))')
L.append(T + 'vid = vid.with_duration(dur).with_fps(30)')
L.append(T + 'return vid')
L.append('')
L.append('')
L.append('def tts(text, out):')
L.append(T + 'from gtts import gTTS')
L.append(T + 'gTTS(text=text, lang=' + q + 'vi' + q + ').save(out)')
L.append('')
L.append('')
L.append('def build(item, out, seed=None):')
L.append(T + 'from ops.compat import get_audio_clip, concat as cc')
L.append(T + 'import random, hashlib')
L.append(T + 'A = get_audio_clip()')
L.append(T + 'os.makedirs(os.path.join(ROOT, ' + q + 'output' + q + '), exist_ok=True)')
L.append(T + 'vo = os.path.join(ROOT, ' + q + 'output' + q + ', ' + q + 'vo5' + q + ' + item[' + q + 'id' + q + '] + ' + q + '.mp3' + q + ')')
L.append(T + 'tts(item[' + q + 'hook' + q + '] + ' + q + ' ' + q + ' + item[' + q + 'body' + q + '] + ' + q + ' ' + q + ' + item[' + q + 'payoff' + q + '], vo)')
L.append(T + 'aud = A(vo)')
L.append(T + 'if aud.duration > TARGET:')
L.append(T + T + 'aud = aud.subclipped(0, min(TARGET, aud.duration))')
L.append(T + 'parts = [(item[' + q + 'hook' + q + '], ' + q + 'yellow' + q + ', 56, 300), (item[' + q + 'body' + q + '], ' + q + 'white' + q + ', 44, 560), (item[' + q + 'payoff' + q + '], ' + q + '#00ffcc' + q + ', 48, 900)]')
L.append(T + 'seg = min(aud.duration, TARGET) / 3.0')
L.append(T + 'scenes = []')
L.append(T + 'for i, (tx, col, fs, y) in enumerate(parts):')
L.append(T + T + 'scenes.append(make_scene(None, tx, col, fs, seg, y, seed=seed + i))')
L.append(T + 'vid = cc(scenes)')
L.append(T + 'vid = vid.with_audio(aud)')
L.append(T + 'vid.write_videofile(out, fps=30, codec=' + q + 'libx264' + q + ', audio_codec=' + q + 'aac' + q + ', logger=None)')
L.append(T + 'return out')
open('ops/content_video5.py', 'w', encoding='utf-8').write(NL.join(L))
print('written', len(L), 'lines')
