u = chr(95) + chr(95)
q = chr(34)
T = chr(9)
p = 'ops/compat.py'
L = []
L.append('# MoviePy v2 compatibility shim')
L.append('import os')
L.append('_local_ff = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(' + u + 'file' + u + '))), ' + q + 'tools' + q + ', ' + q + 'ffmpeg.exe' + q + ')')
L.append('if os.path.exists(_local_ff) and not os.environ.get(' + q + 'IMAGEIO_FFMPEG_EXE' + q + '):')
L.append(T + 'os.environ[' + q + 'IMAGEIO_FFMPEG_EXE' + q + '] = _local_ff')
L.append('')
L.append('try:')
L.append(T + 'from PIL import Image')
L.append(T + 'if not hasattr(Image, ' + q + 'ANTIALIAS' + q + '):')
L.append(T + T + 'Image.ANTIALIAS = Image.LANCZOS')
L.append('except Exception:')
L.append(T + 'pass')
L.append('')
L.append('')
L.append('def _editor():')
L.append(T + 'try:')
L.append(T + T + 'from moviepy.editor import VideoFileClip, AudioFileClip, TextClip, CompositeVideoClip, concatenate_videoclips, ColorClip, ImageClip')
L.append(T + T + 'return VideoFileClip, AudioFileClip, TextClip, CompositeVideoClip, concatenate_videoclips, ColorClip, ImageClip')
L.append(T + 'except Exception:')
L.append(T + T + 'from moviepy import VideoFileClip, AudioFileClip, TextClip, CompositeVideoClip, concatenate_videoclips, ColorClip, ImageClip')
L.append(T + T + 'return VideoFileClip, AudioFileClip, TextClip, CompositeVideoClip, concatenate_videoclips, ColorClip, ImageClip')
L.append('')
L.append('')
L.append('def get_video_clip():')
L.append(T + 'return _editor()[0]')
L.append('')
L.append('')
L.append('def get_audio_clip():')
L.append(T + 'return _editor()[1]')
L.append('')
L.append('')
L.append('def concat(clips):')
L.append(T + 'cc = _editor()[4]')
L.append(T + 'return cc(clips, method=' + q + 'compose' + q + ')')
L.append('')
L.append('')
L.append('def composite(clips):')
L.append(T + 'CC = _editor()[3]')
L.append(T + 'return CC(clips)')
L.append('')
L.append('')
L.append('def get_image_clip():')
L.append(T + 'return _editor()[6]')
L.append('')
L.append('')
L.append('def text_clip(t, fs=48, color=' + q + 'white' + q + ', font=None, size=None, method=' + q + 'caption' + q + '):')
L.append(T + 'TC = _editor()[2]')
L.append(T + 'kw = {}')
L.append(T + 'if font:')
L.append(T + T + 'kw[' + q + 'font' + q + '] = font')
L.append(T + 'return TC(t, fontsize=fs, color=color, stroke_color=' + q + 'black' + q + ', stroke_width=4, size=size, method=method, align=' + q + 'center' + q + ', **kw)')
L.append('')
L.append('')
L.append('def color_clip(size, color, duration):')
L.append(T + 'CC = _editor()[5]')
L.append(T + 'return CC(size, color=color, duration=duration)')
open(p, 'w', encoding='utf-8').write(chr(10).join(L))
print('written ok', len(L))
