import io, os
lines = []
lines.append('# TNT MEDIA - TRANG THAI DASHBOARD DA KENH')
lines.append('')
lines.append('## Kenh dang quan ly')
lines.append('- Mialinhcute (Mia Linh Cute) - anime/roblox/cute_animals/meme - enabled')
lines.append('- vilevi5676 (ViLe Vi) - lifestyle/food/animals/nostalgia/curiosity - enabled (16:9, giong am, video dai)')
lines.append('- whatif_vi - whatif/facts - enabled')
lines.append('')
lines.append('## API quan ly kenh (os_app/router.py)')
lines.append('- GET /os/api/channels - danh sach kenh + so item moi + da dang')
lines.append('- POST /os/api/channels/{id}/toggle?enabled= - bat/tat kenh')
lines.append('- GET /os/api/channels/{id}/content?kind= - noi dung 1 kenh')
lines.append('')
lines.append('## Dashboard tab moi')
lines.append('- Tab Channels: bang kenh, trang thai ON/OFF, kinds, video moi, da dang, nut bat/tat')
lines.append('')
lines.append('## Nang cap caption (channel_style.py)')
lines.append('- Chu nho 44px (truoc 70), dat thap 0.68H, khong che hinh')
lines.append('')
lines.append('## Video da dang phien nay')
lines.append('- Mia: shiba t2lWFofPtHI, quokka Vq08-qYSFr4, dragonball DizX9E9bsa4, mm2 S19vtGTzp1Q')
open('DASHBOARD_CHANNELS.md','w',encoding='utf-8').write(chr(10).join(lines))
print('written')
