import io
NL = chr(10)
lines = [
'# NEXT SESSION - TNT Media Multi-Channel',
'',
'## PHIEN 2026-09-18 (MULTI-CHANNEL SYSTEM)',
'',
'### Da dat duoc',
'1. He thong multi-channel hoan chinh:',
' - channels/<id>/channel.json (config style + content + schedule)',
' - channels/<id>/content_db.json (noi dung rieng)',
' - channels/<id>/topic_pool.json (chu de mo rong)',
' - channels/<id>/token.pickle (OAuth rieng tung kenh)',
' - channels/<id>/published_ledger.json (chong trung rieng tung kenh)',
'2. Module moi:',
' - ops/channel_loader.py (load/validate/list/create channel)',
' - ops/channel_style.py (build video theo style tung kenh)',
' - ops/channel_pipeline.py (chay PDCA 1 kenh)',
' - ops/multichannel_autopilot.py (vong lap tat ca kenh)',
' - ops/channel_cli.py (CLI quan ly kenh)',
'3. Refactor:',
' - ops/content_freshness.py (ledger per-channel + fallback global)',
' - ops/os_publish.py (set_channel + _resolve_token_path)',
'4. Kenh da setup:',
' - whatif_vi: ENABLED, 14 whatif + 22 facts, token OK, ledger 16',
' - Mialinhcute: DISABLED, anime+roblox+cute_animals (6 items), CHUA CO token',
'',
'### CLI',
'- python -m ops.channel_cli list',
'- python -m ops.channel_cli add <id> --name "Ten" --token <path>',
'- python -m ops.channel_cli enable <id> true|false',
'- python -m ops.channel_cli show <id>',
'- python -m ops.channel_cli token <id>',
'- python -m ops.channel_pipeline <id> [batch] # chay 1 kenh',
'- python -m ops.multichannel_autopilot run # chay tat ca kenh enabled',
'- python -m ops.multichannel_autopilot # status',
'- python -m ops.multichannel_autopilot enable true # bat autopilot da kenh',
'',
'### LUU Y KY THUAT QUAN TRONG',
'- Tool write_file NEN leading spaces -> PHAI dung TAB de thut le',
'- Tool write_file bien file -> file, name -> name',
' => Sau khi ghi file .py, chay tools/_fix_all.py de fix',
'- Khong viet file .py dai truc tiep; nen dung script Python sinh file',
'',
'### KENH MIALINHCUTE (moi them)',
'- Chu de: anime (Doraemon, Conan), roblox (Adopt Me, Brookhaven),',
' cute animals (capybara, red panda)',
'- Style: voice female_cute, mau hong #ff69b4 + vang #ffd700,',
' watermark @Mialinhcute, duration toi da 50s',
'- Schedule: 90 phut/lan, batch 2, gio vang 7/11/16/19/21',
'- CAN LAM: dang nhap OAuth de tao channels/Mialinhcute/token.pickle',
' (xem docs/ANALYTICS_SETUP.md, chon dung kenh Mialinhcute khi dang nhap)',
'',
'### VIEC PHIEN SAU',
'1. Tao token.pickle cho Mialinhcute (OAuth 1 lan)',
'2. Test: python -m ops.channel_pipeline Mialinhcute 1',
'3. Mo rong content_db cho Mialinhcute (hien chi 6 items)',
'4. Bat autopilot da kenh: python -m ops.multichannel_autopilot enable true',
'5. OAuth Analytics (docs/ANALYTICS_SETUP.md)',
'6. Nap credit OpenAI de dung AI xin',
'',
'### TICH HOP CONTROL CENTER',
'- Can them API cho multichannel vao ops/control_center.py:',
' GET /api/channels -> list + status',
' POST /api/channel/enable -> {id, enabled}',
' POST /api/channel/run -> {id, batch}',
'',
]
io.open('NEXT_SESSION.md', 'w', encoding='utf-8').write(NL.join(lines) + NL)
print('NEXT_SESSION.md updated')
